import "@/app/styles/globals.css";

import Navbar from "@/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Doctrinaire - an opinionated web-app starter template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="synthwave">
      <body>
        <div className="mockup-browser mx-auto mt-30 max-w-5/6 border border-base-400">
          <div className="mockup-browser-toolbar">
            <div className="input">https://github.com/aaronbassett/doctrinaire</div>
          </div>
          <Navbar />
          <div className="grid min-h-96 place-content-center space-y-10 bg-base-200 py-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
